languageCode = "en-us"
title = "HOT Toolbox"
theme = "hotdocs"
DefaultContentLanguage = "en"
relativeurls = true
enableGitInfo = true

[params]
    GithubRepo = "https://github.com/hotosm/toolbox"

[imaging]
    resampleFilter = "box"
    quality = 75